name: Check that module was compiled

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  compile-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.x.x

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Compile code
        run: pnpm compile

      - name: Check for diff
        run: |
          if ! $(git diff --no-patch --exit-code); then
            echo "Detected uncommitted changes after compiling. Please run 'pnpm compile' and commit the changes."
            exit 1
          fi
